### PR TITLE
ACM-15094: Update default clusterimagesets to supported OCP versions where n=4.18

### PR DESCRIPTION
**Pull request by dtthuynh**
https://issues.redhat.com/browse/ACM-15094

### CODE REVIEW

**Comment by fxiang1** [comment]
Looks like I don't have approve permissions.

**Comment by fxiang1** [comment]
Thanks @xiangjingli !

**Comment by fxiang1** [comment]
Nope, still not working. I need to be added to the OWNERS file. Maybe in another PR :)

**Comment by xiangjingli** [comment]
@fxiang1  I added you to the OWNERS file as the approver and reviewer.  Hopefully this will work :-)

**Comment by fxiang1** [comment]
Thanks @xiangjingli ! It's working now :)

**Pull request merged**
